spring.data.mongodb.uri=mongodb+srv://juan:taller123@eva-u2-spring.vuumqxm.mongodb.net/discografica-db?appName=eva-u2-spring
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration